### ISSUE TITLE
Why not chordpro?

### ISSUE THREAD

**Issue by bkeepers** [SongProOrg/songpro.org#5]
Songpro looks great, but I'm curious how it's different from [chordpro](https://www.chordpro.org/). I don't see any mention of it on the site and was just curious.

**Comment by spilth** [comment]
Thanks! It was definitely inspired by ChordPro (and Markdown)

As for why, the syntax is different -- lighter and more modern in my opinion. I've also found it easier to parse in code than the ChordPro format.

**Comment by bkeepers** [comment]
Makes sense, thanks for the reply. I agree it looks cleaner and more modern. Now to get other tools to support it...

**Comment by spilth** [comment]
You’re inquiry got me thinking that we should probably add the ability to render a SongPro song as a ChordPro text file, in addition to HTML.
